[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "base-pyfile"
version = {version = "*", file = "__init__.py"}
description = ""
authors = ["Paalon <paalon@email.adress>"]
readme = "README.md"